DATA SEGMENT  
    
DATA1 DB 'SINGLE PLAYER "S"','$'
DATA2 DB 'TWO PLAYER "T"','$'
DATA3 DB 'CREDITS "C"','$'
DATA4 DB 'EXIT "ESC"','$'   

PLAYER DB 15 DUP(0),'$' 
DATA_PLAYER DB 'Enter the Player name :','$'

PLAYER1 DB 15 DUP(0),'$'
DATA_PLAYER1 DB 'Enter the Player 1 name :','$'
 
PLAYER2 DB 15 DUP(0),'$'  
DATA_PLAYER2 DB 'Enter the Player 2 name :','$' 

PLAY1 DB 'Player 1:','$' 
PLAY2 DB 'Player 2:','$'  

DICE_NUMBER DB 1 DUP(0) 
SCORE DB 1 DUP(0)  
SCORE1 DB 1 DUP(0)
SCORE2 DB 1 DUP(0)  

WIN_MSG1 DB "The Winner is ",'$'
WIN_MSG2 DB "Nice try, better luck next time",'$'

DC1 DB 'Dice1:','$'
DC2 DB 'Dice2:','$' 

DICE4 DB 1 DUP(0) 
DICE5 DB 1 DUP(0)
DICE6 DB 1 DUP(0)


                          
VASE1 DB '                    \____/  ','$' 
VASE2 DB '                   \      /','$' 
VASE3 DB '                  \        /	','$' 
VASE4 DB '                 \~~~~~~~~~~/','$'  

LEGS1 DB '                  :--""--""--:','$' 
LEGS2 DB '                     //\\ ','$' 

BODY1 DB '                     \  /','$'  
BODY2 DB '                    {    }','$'
BODY3 DB '                    V   \','$'


LWING1 DB '            .-~~.   ','$'
LWING2 DB '        .-~.-~.- `. ','$'
LWING3 DB '    .-~.-~.-~.-~.  \','$' 
LWING4 DB '.-~.-~.-~.-~.-~.-~. ','$'
LWING5 DB '         ~  ~.-~.- ','$'
LWING6 DB '               ~ -~.~','$' 

RWING1 DB '.~~-.              ','$'
RWING2 DB ".' -.~-.~-.          ",'$'
RWING3 DB '/  .~-.~-.~-.~-.      ','$' 
RWING4 DB '/ .~-.~-.~-.~-.~-.~-.  ','$'
RWING5 DB '-.~-.~  ~              ','$'
RWING6 DB '~.~- ~                 ','$'

HEAD1 DB '.--.','$'
HEAD2 DB '{ O ]]>','$'
HEAD3 DB '| |  ','$'

                         

CRED1 DB 'SAMED SIMSEK','$' 
CRED2 DB '21783336','$'  
CRED3 DB 'HACETTEPE UNIVERSITY','$'
CRED4 DB 'ELECTRICAL AND ELECTRONIC ENGINEERING','$'
CRED5 DB 'ELE338-MICROPROCESSOR ARCHITECTURE AND PROGRAMMING LAB.','$'
    
DATA ENDS

STACK SEGMENT  
    DW   128  DUP(0)
STACK ENDS

CODE SEGMENT
START:

MOV AX,DATA
MOV DS,AX

MOV AH,00H
MOV AL,03H;SET VIDEO MODE
INT 10H

MENU: 
MOV AH,05H
MOV AL,0  ;SET PAGE 0
INT 10H 

MOV DH,5  ;ROW
MOV DL,25  ;COLUMN
MOV BH,0  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DATA1 
MOV AH,09H  ;PRINT DATA1
INT 21H 

MOV DH,7  ;ROW
MOV DL,25  ;COLUMN
MOV BH,0  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DATA2
MOV AH,09H ;PRINT DATA2
INT 21H

MOV DH,9  ;ROW
MOV DL,25  ;COLUMN
MOV BH,0  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DATA3
MOV AH,09H ;PRINT DATA3
INT 21H 

MOV DH,11  ;ROW
MOV DL,25  ;COLUMN
MOV BH,0  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DATA4
MOV AH,09H ;PRINT DATA4
INT 21H  

GET_CHAR:

MOV AH,07H ;GET A CHARACTER
INT 21H

CMP AL,01BH  ;PRESS "ESC" FOR EXITTING THE GAME
JE EXIT   

CMP AL,5BH
JB UPPER

SUB AL,20H ;CONVERT THE LETTER FROM LOWERCASE TO UPPERCASE

UPPER:

CMP AL,053H  ;PRESS "S" TO GO TO SINGLE PLAYER
JE SINGLE_P 

CMP AL,054H  ;PRESS "T" TO GO TO TWO PLAYER
JE TWO_P

CMP AL,043H  ;PRESS "C" TO GO TO CREDITS
JE CREDITS

JMP GET_CHAR ;GET A NEW LETTER




;SELECT SINGLE PLAYER MODE
 
SINGLE_P:
MOV DS:[SCORE1],0 
MOV DS:[SCORE2],0 

MOV AH,05H
MOV AL,1  ;SET PAGE 1
INT 10H 

MOV DH,5  ;ROW
MOV DL,5  ;COLUMN
MOV BH,1  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DATA_PLAYER 
MOV AH,09H  ;PRINT DATA_PLAYER
INT 21H 
         
LEA SI,PLAYER

WRITE_NAME:
MOV AH,01H
INT 21H  
CMP AL,0H ;IF PRESSED CAPSLOCK,GET A NEW LETTER
JE WRITE_NAME 
CMP AL,0DH ;PRESS ENTER TO BEGIN THE GAME
JE BEGIN

CMP AL,5BH
JB UPPER1
SUB AL,20H ;CONVERT THE LETTER FROM LOWERCASE TO UPPERCASE
UPPER1:
MOV [SI],AL 
INC SI        
JMP WRITE_NAME 


BEGIN: 
;INITIALIZE
MOV DS:[SCORE],0 
MOV DS:[DICE4],0
MOV DS:[DICE5],0
MOV DS:[DICE6],0
 

CALL GAME_SCREEN    
MOV AH,05H
MOV AL,2  ;SET PAGE 2
INT 10H 
MOV DH,2  ;ROW
MOV DL,3  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET PLAY1 
MOV AH,09H  ;PRINT PLAY1 
INT 21H  
MOV DH,2  ;ROW
MOV DL,60  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET PLAY2 
MOV AH,09H  ;PRINT PLAY2 
INT 21H 

MOV DH,3  ;ROW
MOV DL,6  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DC1 
MOV AH,09H  ;PRINT DC1 
INT 21H  
MOV DH,3  ;ROW
MOV DL,63  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DC2 
MOV AH,09H  ;DC2 
INT 21H 

;PRINT SCORE1
MOV DH,2  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[SCORE1]
ADD AL,30H
MOV AH,0EH  ;PRINT SCORE1 
INT 10H
;PRINT SCORE2
MOV DH,2  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[SCORE2]
ADD AL,30H
MOV AH,0EH  ;PRINT SCORE2 
INT 10H  

DICE1_P1:;FIRST DICE FOR PLAYER 1
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE1_P1

CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,1
JNE DICE1_P2

CALL PRINT_VASE

ADD DS:[SCORE],1
JMP DICE2_P1

DICE1_P2:;FIRST DICE FOR COMPUTER
 
CALL RANDOM_DICE   
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H  

MOV AL,DS:[DICE_NUMBER]
CMP AL,1 
JNE DICE1_P1  

CALL PRINT_VASE
ADD DS:[SCORE],1
JMP DICE2_P2 

DICE2_P1:;SECOND DICE FOR PLAYER 1
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE2_P1

CALL RANDOM_DICE 

;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,2
JNE DICE2_P2

CALL PRINT_LEGS
ADD DS:[SCORE],1
JMP DICE3_P1

DICE2_P2:;SECOND DICE FOR COMPUTER
 
CALL RANDOM_DICE 
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,2 
JNE DICE2_P1  

CALL PRINT_LEGS
ADD DS:[SCORE],1
JMP DICE3_P2  

DICE3_P1:;THIRD DICE FOR PLAYER 1
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE3_P1

CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,3
JNE DICE3_P2

CALL PRINT_BODY
ADD DS:[SCORE],1
JMP DICE4_P1

DICE3_P2:;THIRD DICE FOR COMPUTER
 
CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H  

MOV AL,DS:[DICE_NUMBER]
CMP AL,3 
JNE DICE3_P1  

CALL PRINT_BODY
ADD DS:[SCORE],1
JMP DICE4_P2 

DICE4_P1: ;4TH DICE FOR PLAYER 1
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE4_P1

CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,4
JB DICE4_P2 


CMP AL,4 
JNE OTHR
MOV AL,DS:[DICE4] 
CMP AL,0
JNE DICE4_P2
MOV DS:[DICE4],1
CALL PRINT_LWING
ADD DS:[SCORE],1
MOV AL,DS:[SCORE]  
CMP AL,6
JE P1_WIN
JMP DICE4_P1

OTHR:
CMP AL,5
JNE OTHR1
MOV AL,DS:[DICE5] 
CMP AL,0
JNE DICE4_P2
MOV DS:[DICE5],1 
CALL PRINT_RWING 
ADD DS:[SCORE],1
MOV AL,DS:[SCORE]  
CMP AL,6
JE P1_WIN
JMP DICE4_P1

OTHR1:
CMP AL,6
JNE DICE4_P2 
MOV AL,DS:[DICE6] 
CMP AL,0
JNE DICE4_P2
MOV DS:[DICE6],1
CALL PRINT_HEAD
ADD DS:[SCORE],1 
MOV AL,DS:[SCORE]  
CMP AL,6
JE P1_WIN
JMP DICE4_P1





DICE4_P2:  ;4TH DICE FOR COMPUTER
CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H


MOV AL,DS:[DICE_NUMBER]
CMP AL,4 
JB DICE4_P1
 
CMP AL,4 
JNE OTHR2 
MOV AL,DS:[DICE4] 
CMP AL,0
JNE DICE4_P1
MOV DS:[DICE4],1
CALL PRINT_LWING
ADD DS:[SCORE],1 
MOV AL,DS:[SCORE]  
CMP AL,6
JE COM_WIN
JMP DICE4_P1

OTHR2:
CMP AL,5
JNE OTHR3  
MOV AL,DS:[DICE5] 
CMP AL,0
JNE DICE4_P1
MOV DS:[DICE5],1
CALL PRINT_RWING 
ADD DS:[SCORE],1
MOV AL,DS:[SCORE]  
CMP AL,6
JE COM_WIN
JMP DICE4_P1

OTHR3:
CMP AL,6
JNE DICE4_P2 
MOV AL,DS:[DICE6] 
CMP AL,0
JNE DICE4_P1
MOV DS:[DICE6],1
CALL PRINT_HEAD
ADD DS:[SCORE],1
MOV AL,DS:[SCORE]  
CMP AL,6
JE COM_WIN
JMP DICE4_P1

COM_WIN: 
ADD DS:[SCORE2],1

MOV AL,DS:[SCORE2]  
CMP AL,3
JE WIN1
CMP AL,2
JNE BEGIN
MOV AL,DS:[SCORE1] ;IF COMPUTER WINS FIRST TWO ROUND,WIN THE GAME
CMP AL,0
JNE BEGIN

WIN1: 
MOV DH,2  ;ROW
MOV DL,20  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET WIN_MSG2 
MOV AH,09H  ;PRINT WIN_MSG2  
INT 21H

MOV AH,07H ;GET A CHARACTER
INT 21H 

CMP AL,1BH  ;PRESS "ESC" TO EXIT TO GAME
JE EXIT  
JMP MENU

P1_WIN:
ADD DS:[SCORE1],1

MOV AL,DS:[SCORE1]  
CMP AL,3
JE WIN2
CMP AL,2
JNE BEGIN
MOV AL,DS:[SCORE2] ;IF PLAYER 1 WINS FIRST TWO ROUND,WIN THE GAME
CMP AL,0
JNE BEGIN

WIN2: 
MOV DH,2  ;ROW
MOV DL,20  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET WIN_MSG1 
MOV AH,09H  ;PRINT WIN_MSG1 
INT 21H 
MOV DH,2  ;ROW
MOV DL,35  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET PLAYER 
MOV AH,09H  ;PRINT PLAYER 
INT 21H 

MOV AH,07H ;GET A CHARACTER
INT 21H 

CMP AL,1BH  ;PRESS "ESC" TO EXIT TO GAME
JE EXIT  
JMP MENU



TWO_P:
MOV DS:[SCORE1],0 
MOV DS:[SCORE2],0 


MOV AH,05H
MOV AL,3  ;SET PAGE 3
INT 10H 

MOV DH,5  ;ROW
MOV DL,5  ;COLUMN
MOV BH,3  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DATA_PLAYER1 
MOV AH,09H  ;PRINT DATA_PLAYER1
INT 21H 
         
LEA SI,PLAYER1

WRITE_NAME1:
MOV AH,01H
INT 21H  
CMP AL,0H ;IF PRESSED CAPSLOCK,GET A NEW LETTER
JE WRITE_NAME1 
CMP AL,0DH ;PRESS ENTER TO BEGIN THE GAME
JE NEXT_NAME2

CMP AL,5BH
JB UPPER2
SUB AL,20H ;CONVERT THE LETTER FROM LOWERCASE TO UPPERCASE
UPPER2:
MOV [SI],AL 
INC SI        
JMP WRITE_NAME1 


NEXT_NAME2:

MOV DH,8  ;ROW
MOV DL,5  ;COLUMN
MOV BH,3  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DATA_PLAYER2 
MOV AH,09H  ;PRINT DATA_PLAYER2
INT 21H 
         
LEA SI,PLAYER2

WRITE_NAME2:
MOV AH,01H
INT 21H  
CMP AL,0H ;IF PRESSED CAPSLOCK,GET A NEW LETTER
JE WRITE_NAME2 
CMP AL,0DH ;PRESS ENTER TO BEGIN THE GAME
JE BEG

CMP AL,5BH
JB UPPER3
SUB AL,20H ;CONVERT THE LETTER FROM LOWERCASE TO UPPERCASE
UPPER3:
MOV [SI],AL 
INC SI        
JMP WRITE_NAME2 

BEG: 
;INITIALIZE
MOV DS:[SCORE],0 
MOV DS:[DICE4],0
MOV DS:[DICE5],0
MOV DS:[DICE6],0

CALL GAME_SCREEN    
MOV AH,05H
MOV AL,2  ;SET PAGE 1
INT 10H 
MOV DH,2  ;ROW
MOV DL,3  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET PLAY1 
MOV AH,09H  ;PRINT PLAY1 
INT 21H  
MOV DH,2  ;ROW
MOV DL,60  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET PLAY2 
MOV AH,09H  ;PRINT PLAY2 
INT 21H 

MOV DH,3  ;ROW
MOV DL,6  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DC1 
MOV AH,09H  ;PRINT DC1 
INT 21H  
MOV DH,3  ;ROW
MOV DL,63  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET DC2 
MOV AH,09H  ;DC2 
INT 21H 

;PRINT SCORE1
MOV DH,2  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[SCORE1]
ADD AL,30H
MOV AH,0EH  ;PRINT SCORE1 
INT 10H
;PRINT SCORE2
MOV DH,2  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[SCORE2]
ADD AL,30H
MOV AH,0EH  ;PRINT SCORE2 
INT 10H  

DICE1_P11:;FIRST DICE FOR PLAYER 1
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE1_P11

CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,1
JNE DICE1_P22

CALL PRINT_VASE

ADD DS:[SCORE],1
JMP DICE2_P11

DICE1_P22:;FIRST DICE FOR PLAYER 2

MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE1_P22
 
CALL RANDOM_DICE   
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H  

MOV AL,DS:[DICE_NUMBER]
CMP AL,1 
JNE DICE1_P11  

CALL PRINT_VASE
ADD DS:[SCORE],1
JMP DICE2_P22 

DICE2_P11:;SECOND DICE FOR PLAYER 1
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE2_P11

CALL RANDOM_DICE 

;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,2
JNE DICE2_P22

CALL PRINT_LEGS
ADD DS:[SCORE],1
JMP DICE3_P11

DICE2_P22:;SECOND DICE FOR PLAYER 2
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE1_P22
 
CALL RANDOM_DICE 
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,2 
JNE DICE2_P11  

CALL PRINT_LEGS
ADD DS:[SCORE],1
JMP DICE3_P22  

DICE3_P11:;THIRD DICE FOR PLAYER 1
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE3_P11

CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,3
JNE DICE3_P22

CALL PRINT_BODY
ADD DS:[SCORE],1
JMP DICE4_P11

DICE3_P22:;THIRD DICE FOR PLAYER 2
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE1_P22
 
CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H   

MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H  

MOV AL,DS:[DICE_NUMBER]
CMP AL,3 
JNE DICE3_P11  

CALL PRINT_BODY
ADD DS:[SCORE],1
JMP DICE4_P22 

DICE4_P11: ;4TH DICE FOR PLAYER 1
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE4_P11

CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,13  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H 

MOV AL,DS:[DICE_NUMBER]
CMP AL,4
JB DICE4_P22 


CMP AL,4 
JNE OTH
MOV AL,DS:[DICE4] 
CMP AL,0
JNE DICE4_P22

MOV DS:[DICE4],1
CALL PRINT_LWING
ADD DS:[SCORE],1
MOV AL,DS:[SCORE]  
CMP AL,6
JE P11_WIN
JMP DICE4_P11

OTH:
CMP AL,5
JNE OTH1
MOV AL,DS:[DICE5] 
CMP AL,0
JNE DICE4_P22
MOV DS:[DICE5],1 
CALL PRINT_RWING 
ADD DS:[SCORE],1
MOV AL,DS:[SCORE]  
CMP AL,6
JE P11_WIN
JMP DICE4_P11

OTH1:
CMP AL,6
JNE DICE4_P22 
MOV AL,DS:[DICE6] 
CMP AL,0
JNE DICE4_P22
MOV DS:[DICE6],1
CALL PRINT_HEAD
ADD DS:[SCORE],1 
MOV AL,DS:[SCORE]  
CMP AL,6
JE P11_WIN
JMP DICE4_P11





DICE4_P22:  ;4TH DICE FOR PLAYER 2
MOV AH,07H
INT 21H

CMP AL,20H
JNE DICE1_P22

CALL RANDOM_DICE
;PRINT DICE NUMBER
MOV DH,3  ;ROW
MOV DL,70  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV AL,DS:[DICE_NUMBER]
ADD AL,30H
MOV AH,0EH  ;PRINT DICE_NUMBER 
INT 10H


MOV AL,DS:[DICE_NUMBER]
CMP AL,4 
JB DICE4_P11
 
CMP AL,4 
JNE OTH2 
MOV AL,DS:[DICE4] 
CMP AL,0
JNE DICE4_P11
MOV DS:[DICE4],1
CALL PRINT_LWING
ADD DS:[SCORE],1 
MOV AL,DS:[SCORE]  
CMP AL,6
JE P22_WIN
JMP DICE4_P11

OTH2:
CMP AL,5
JNE OTH3  
MOV AL,DS:[DICE5] 
CMP AL,0
JNE DICE4_P11
MOV DS:[DICE5],1
CALL PRINT_RWING 
ADD DS:[SCORE],1
MOV AL,DS:[SCORE]  
CMP AL,6
JE P22_WIN
JMP DICE4_P11

OTH3:
CMP AL,6
JNE DICE4_P22 
MOV AL,DS:[DICE6] 
CMP AL,0
JNE DICE4_P11
MOV DS:[DICE6],1
CALL PRINT_HEAD
ADD DS:[SCORE],1
MOV AL,DS:[SCORE]  
CMP AL,6
JE P22_WIN
JMP DICE4_P11

P22_WIN: 
ADD DS:[SCORE2],1

MOV AL,DS:[SCORE2]  
CMP AL,3
JE WIN11
CMP AL,2
JNE BEG
MOV AL,DS:[SCORE1] ;IF COMPUTER WINS FIRST TWO ROUND,WIN THE GAME
CMP AL,0
JNE BEG

WIN11: 
MOV DH,2  ;ROW
MOV DL,20  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET WIN_MSG1 
MOV AH,09H  ;PRINT WIN_MSG1 
INT 21H 
MOV DH,2  ;ROW
MOV DL,35  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET PLAYER2 
MOV AH,09H  ;PRINT PLAYER2 
INT 21H 

MOV AH,07H ;GET A CHARACTER
INT 21H 

CMP AL,1BH  ;PRESS "ESC" TO EXIT TO GAME
JE EXIT  
JMP MENU

P11_WIN:
ADD DS:[SCORE1],1

MOV AL,DS:[SCORE1]  
CMP AL,3
JE WIN22
CMP AL,2
JNE BEG
MOV AL,DS:[SCORE2] ;IF PLAYER 1 WINS FIRST TWO ROUND,WIN THE GAME
CMP AL,0
JNE BEG

WIN22: 
MOV DH,2  ;ROW
MOV DL,20  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET WIN_MSG1 
MOV AH,09H  ;PRINT WIN_MSG1 
INT 21H 
MOV DH,2  ;ROW
MOV DL,35  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET PLAYER1 
MOV AH,09H  ;PRINT PLAYER1 
INT 21H 

MOV AH,07H ;GET A CHARACTER
INT 21H 

CMP AL,1BH  ;PRESS "ESC" TO EXIT TO GAME
JE EXIT  
JMP MENU



CREDITS:

MOV AH,05H
MOV AL,5  ;SET PAGE 5
INT 10H 

MOV DH,5  ;ROW
MOV DL,10  ;COLUMN
MOV BH,5  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET CRED1 
MOV AH,09H  ;PRINT CRED1
INT 21H 

MOV DH,7  ;ROW
MOV DL,10  ;COLUMN
MOV BH,5  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET CRED2
MOV AH,09H ;PRINT CRED2
INT 21H

MOV DH,9  ;ROW
MOV DL,10  ;COLUMN
MOV BH,5  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET CRED3
MOV AH,09H ;PRINT CRED3
INT 21H 

MOV DH,11  ;ROW
MOV DL,10  ;COLUMN
MOV BH,5  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET CRED4
MOV AH,09H ;PRINT CRED4
INT 21H   

MOV DH,13  ;ROW
MOV DL,10  ;COLUMN
MOV BH,5  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET CRED5
MOV AH,09H ;PRINT CRED5
INT 21H

MOV AH,07H ;GET A CHARACTER
INT 21H 

CMP AL,1BH  ;PRESS "ESC" TO EXIT TO GAME
JE EXIT  
JMP MENU


EXIT:
HLT  


GAME_SCREEN PROC 
MOV AH,05H
MOV AL,2  ;SET PAGE 1
INT 10H
;CLEAR SCREEN    
MOV AH,06H
MOV AL,00H
MOV BH,000001111B
MOV CX,0000
MOV DX,184FH
INT 10H  

MOV DH,0  ;ROW
MOV DL,0  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H   
MOV CX,79
UPPER_SIDE:
MOV DL,58H
MOV AH,02H  ;PRINT A CHARACTER
INT 21H 
LOOP UPPER_SIDE

MOV DH,0  ;ROW
MOV DL,79  ;COLUMN

MOV CX,24
RIGHT_SIDE:
PUSH DX 
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H  
MOV DL,58H
MOV AH,02H  ;PRINT A CHARACTER
INT 21H  
POP DX 
INC DH
LOOP RIGHT_SIDE 

MOV DH,23  ;ROW
MOV DL,0  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H   
MOV CX,79
LOWER_SIDE:
MOV DL,58H
MOV AH,02H  ;PRINT A CHARACTER
INT 21H 
LOOP LOWER_SIDE

MOV DH,0  ;ROW
MOV DL,0  ;COLUMN

MOV CX,24
LEFT_SIDE:
PUSH DX 
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H  
MOV DL,58H
MOV AH,02H  ;PRINT A CHARACTER
INT 21H  
POP DX 
INC DH
LOOP LEFT_SIDE

RET
GAME_SCREEN ENDP  


RANDOM_DICE PROC
MOV AX,0H
INT 1AH  
MOV AX,DX            
MOV DX,0H            
MOV BX,6            
DIV BX
ADD DX,1  
MOV DS:[DICE_NUMBER],DL 
RET
RANDOM_DICE ENDP


PRINT_VASE PROC 
MOV AH,05H
MOV AL,2  ;SET PAGE 1
INT 10H  

MOV DH,20  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET VASE1 
MOV AH,09H  ;PRINT VASE1
INT 21H 

MOV DH,19  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET VASE2 
MOV AH,09H  ;PRINT VASE2
INT 21H  

MOV DH,18  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET VASE3 
MOV AH,09H  ;PRINT VASE3
INT 21H 

MOV DH,17  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET VASE4 
MOV AH,09H  ;PRINT VASE4
INT 21H 
    
RET
PRINT_VASE ENDP

PRINT_LEGS PROC 
MOV AH,05H
MOV AL,2  ;SET PAGE 1
INT 10H  

MOV DH,16  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET LEGS1 
MOV AH,09H  ;PRINT LEGS1
INT 21H 

MOV DH,15  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET LEGS2 
MOV AH,09H  ;PRINT LEGS2
INT 21H  
    
RET
PRINT_LEGS ENDP 

PRINT_BODY PROC 
MOV AH,05H
MOV AL,2  ;SET PAGE 1
INT 10H  

MOV DH,14  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET BODY1 
MOV AH,09H  ;PRINT BODY1
INT 21H 

MOV DH,13  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET BODY2 
MOV AH,09H  ;PRINT BODY2
INT 21H 

MOV DH,12  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET BODY3 
MOV AH,09H  ;PRINT BODY3
INT 21H 
   
RET
PRINT_BODY ENDP



PRINT_LWING PROC 
MOV AH,05H
MOV AL,2  ;SET PAGE 1
INT 10H  

MOV DH,9  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET LWING1 
MOV AH,09H  ;PRINT LWING1
INT 21H 

MOV DH,10  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET LWING2 
MOV AH,09H  ;PRINT LWING2
INT 21H  

MOV DH,11  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET LWING3 
MOV AH,09H  ;PRINT LWING3
INT 21H 

MOV DH,12  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET LWING4 
MOV AH,09H  ;PRINT LWING4
INT 21H 

MOV DH,13  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET LWING5 
MOV AH,09H  ;PRINT LWING5
INT 21H 

MOV DH,14  ;ROW
MOV DL,10  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET LWING6 
MOV AH,09H  ;PRINT LWING6
INT 21H
    
RET
PRINT_LWING ENDP

PRINT_RWING PROC 
MOV AH,05H
MOV AL,2  ;SET PAGE 1
INT 10H 

MOV DH,9  ;ROW
MOV DL,39  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET RWING1 
MOV AH,09H  ;PRINT RWING1
INT 21H 

MOV DH,10  ;ROW
MOV DL,37  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET RWING2 
MOV AH,09H  ;PRINT RWING2
INT 21H  

MOV DH,11  ;ROW
MOV DL,36  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET RWING3 
MOV AH,09H  ;PRINT RWING3
INT 21H 

MOV DH,12  ;ROW
MOV DL,35  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET RWING4 
MOV AH,09H  ;PRINT RWING4
INT 21H 

MOV DH,13  ;ROW
MOV DL,37  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET RWING5 
MOV AH,09H  ;PRINT RWING5
INT 21H 

MOV DH,14  ;ROW
MOV DL,36  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET RWING6 
MOV AH,09H  ;PRINT RWING6
INT 21H
    
RET
PRINT_RWING ENDP 

PRINT_HEAD PROC 
MOV AH,05H
MOV AL,2  ;SET PAGE 1
INT 10H

MOV DH,9  ;ROW
MOV DL,31  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET HEAD1 
MOV AH,09H  ;PRINT HEAD1
INT 21H 

MOV DH,10  ;ROW
MOV DL,30  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET HEAD2 
MOV AH,09H  ;PRINT HEAD2
INT 21H 

MOV DH,11  ;ROW
MOV DL,31  ;COLUMN
MOV BH,2  ;PAGE NUMBER
MOV AH,02H ;SET CURSOR POSITION
INT 10H
MOV DX,OFFSET HEAD3 
MOV AH,09H  ;PRINT HEAD3
INT 21H 
    
RET
PRINT_HEAD ENDP 


    
CODE ENDS

END START
